project:
  type: website
  output-dir: docs

website:
  title: "OPEL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: join.qmd
        text: Join Us

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

