project:
  type: website
  output-dir: docs

website:
  title: "OPEL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

