---
title: "Opportunities"
---

Ways to join OPEL.

## Postdoc positions

None at the moment, but we are happy to support applications with opportunities such as:

-   1851 Research Fellowships: <https://royalcommission1851.org/fellowships/research-fellowships>

-   Leverhulme Trust Early Career Fellowships: <https://www.leverhulme.ac.uk/early-career-fellowships>

-   Marie-Sklodowska Curie Postdoctoral Fellowships: <https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships>

-   Royal Society Newton International Fellowships: <https://royalsociety.org/grants/newton-international/>

## PhDs

We generally recruit PhDs through the University of Southampton's [IGNITE Doctoral Landscape Award](https://ignite-dla.soton.ac.uk/). For details of how to apply: <https://ignite-dla.soton.ac.uk/ignite-apply/>.

Prospective students should also contact Dr. Ryan Reisinger (r.r.reisinger \[at\] southampton.ac.uk) and send a short motivation, CV and transcript of academic results.

If you have another funding source for a PhD (e.g., your own national funding competition for PhD studies abroad), please, get in touch and include information on the funding source.

Current opportunities co-supervised by Dr Reisinger:

-   **Global blue corridors for marine megafauna**\
    Dr Ryan Reisinger, Prof. David Sims, Mr Chris Johnson\
    <https://www.findaphd.com/phds/project/global-blue-corridors-for-marine-megafauna/?p187842>

-   **Future-proofing marine conservation: millennial-scale climate change impacts on ocean ecosystems\
    **Dr Richard Stockey, Dr Ryan Reisinger, Prof. Tom Gernon\
    <https://www.findaphd.com/phds/project/future-proofing-marine-conservation-millennial-scale-climate-change-impacts-on-ocean-ecosystems/?p187876>

-   **Living Seascapes: Biodiversity, Ecosystem Services, and Equitable Marine Conservation in the Western Indian Ocean\
    **Dr Gwilym Rowlands, Dr Ryan Reisinger\
    <https://www.findaphd.com/phds/project/living-seascapes-biodiversity-ecosystem-services-and-equitable-marine-conservation-in-the-western-indian-ocean/?p187891>

## Undergrad

For Southampton undergraduate students, Ryan Reisinger supervises Independent Research Projects (SOES3046) and Advanced Independent Research Projects (SOES6086) on BSc and MSci degree programmes in the School of Ocean and Earth Science. Get in touch with him as early as you can (normally a year in advance) as project slots fill up quickly. Please a short paragraph on your academic interests and motivation, and your academic results so far.

## Lab meetings

If you're a Southampton student or staff member and you would like to join our lab group, including our regular meetings, please [fill in this quick form](https://forms.office.com/e/NcppBann2k).
