- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.tree.2024.09.009
  image: https://www.cell.com/cms/10.1016/j.tree.2024.09.009/asset/4f29319d-cc3a-450d-b670-c0015e7a9269/main.assets/gr1_lrg.jpg

- id: doi:10.1111/cobi.14345
  image: https://conbio.onlinelibrary.wiley.com/cms/asset/319c905a-f3b3-4562-a83a-f1d812852cc0/cobi14345-fig-0002-m.jpg

- id: doi:10.1111/brv.13066
  image: https://onlinelibrary.wiley.com/cms/asset/8d361218-b87e-47d2-afea-b861bc4670f0/brv13066-fig-0001-m.jpg
  
